spring:
  datasource:
    primary:
        url: jdbc:mysql://44.19.28.108:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        jdbc-url: jdbc:mysql://44.19.28.108:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
    secondary:
        url: jdbc:mysql://44.19.28.108:3306/yjtorgfep?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        jdbc-url: jdbc:mysql://44.19.28.108:3306/yjtorgfep?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456        